### ISSUE TITLE
Differences between zerotier/zerotier and zerotier/zerotier-synology

### ISSUE THREAD

**Issue by palonsoro** [zerotier/zerotier-synology#6]
I am just curious, why is there a maintained docker image specific for Synology NAS when there is a generic docker image for zerotier? What are the differences (apart from stuff like one image being Debian-based and the other one being Alpine-based)? 

Thanks and regards.

**Comment by joseph-henry** [comment]
At the time of creation our `zerotier/zerotier` docker image was different enough to prevent it from working on Synology. I don't quite remember the issue but I think it wasn't correctly assigning IP addresses to the host's interfaces.
