### ISSUE TITLE
is the Update 1.86 for Synology correct?

### ISSUE THREAD

**Issue by Infoman68** [zerotier/zerotier-synology#7]
FROM alpine:3.13 as builder

ARG COMMIT=4a2c75a60941e75f36ed1961458a42fbd12ea4ac

RUN apk add --update alpine-sdk linux-headers \
  && git clone --quiet https://github.com/zerotier/ZeroTierOne.git /src \
  && git -C src reset --quiet --hard ${COMMIT} \
  && cd /src \
  && make -f make-linux.mk

FROM alpine:3.13
LABEL version="1.8.4"     <-----------------------------------------------------------------????
LABEL description="ZeroTier One docker image for Synology NAS"

RUN apk add --update --no-cache libc6-compat libstdc++

EXPOSE 9993/udp

COPY --from=builder /src/zerotier-one /usr/sbin/
RUN mkdir -p /var/lib/zerotier-one \
  && ln -s /usr/sbin/zerotier-one /usr/sbin/zerotier-idtool \
  && ln -s /usr/sbin/zerotier-one /usr/sbin/zerotier-cli

ENTRYPOINT ["zerotier-one"]

**Comment by joseph-henry** [comment]
You're correct. Thanks for pointing this out. Fixed, closing this ticket.
