### ISSUE TITLE
Update to 1.86 still don't work - docker pull gets 3 month old image

### ISSUE THREAD

**Issue by Infoman68** [zerotier/zerotier-synology#8]
16.03.2022 -> trying Update to 1.86

root@xxxxxxxx:/# docker rmi be6c30933942
Untagged: zerotier/zerotier-synology:latest
Untagged: zerotier/zerotier-synology@sha256:ae4bbacb12d4d0f16c992d42f88e6bf547451c49a5c3fb19995adc9ed81514a3
Deleted: sha256:be6c30933942b49baa20039d05bb5322b8b9321d7349d983fb98570dc158853d
Deleted: sha256:dc83d64c2fe7894cf07d5695866fbcf4b614585cbbf6dc8e1c46495af8de7e8d
Deleted: sha256:7d78869198138a33bf77f3fc78a3f5739c311fc8dbc6c85ac8ffd216a0163064
Deleted: sha256:b0882d4e8b9d79b0e622dd20ebb11aadd70f06299a167ddff298a286b3d4e119
Deleted: sha256:7fcb75871b2101082203959c83514ac8a9f4ecfee77a0fe9aa73bbe56afdf1b4

root@xxxxxxxx:/# docker pull zerotier/zerotier-synology:latest                    latest: Pulling from zerotier/zerotier-synology
5758d4e389a3: Pull complete
721717cf4e07: Pull complete
ef05f4383823: Pull complete
7a5376e38df6: Pull complete
Digest: sha256:ae4bbacb12d4d0f16c992d42f88e6bf547451c49a5c3fb19995adc9ed81514a3
Status: Downloaded newer image for zerotier/zerotier-synology:latest
docker.io/zerotier/zerotier-synology:latest

root@xxxxxxx:/# docker exec -it zt zerotier-cli status
200 info 1b2ecexxxx 1.8.4 ONLINE
root@xxxxxxx:/# docker images -a
zerotier/zerotier-synology   latest    be6c30933942   3 months ago    10.2MB

**Comment by joseph-henry** [comment]
Updated. Thanks for reporting.
